alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias ls='ls --color'
alias l='ls -lhA'
alias ll='ls -l'
alias la='l'
alias c='clear'
# alias eas="bunx eas-cli"
alias expo-doctor="bunx expo-doctor"
