brew "bat"
brew "bun"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git-delta"
brew "gnupg"
brew "go"
brew "htop"
brew "jq"
brew "mise"
brew "node"
brew "ripgrep"
brew "stow"
brew "tree"
brew "uv"
brew "wget"
brew "zoxide"

uv "graphifyy"
uv "markitdown[all]"

code_cli = ["/opt/homebrew/bin/code", "/usr/local/bin/code", "/usr/bin/code", "/snap/bin/code",
            File.expand_path("~/.local/bin/code")].any? { |p| File.executable?(p) }
instance_eval(File.read(File.expand_path("Brewfile.vscode", __dir__))) if code_cli

instance_eval(File.read(File.expand_path("Brewfile.mac", __dir__))) if OS.mac?

local_brewfile = File.expand_path("~/.Brewfile.local")
instance_eval(File.read(local_brewfile)) if File.exist?(local_brewfile)
