[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  { key = "Right", mods = "Command", chars = "\u0005" },
  { key = "Left", mods = "Command", chars = "\u0001" },
]
